### PR TITLE
Scouting form to storage

### LINKED ISSUE #60: Make the graphs bigger
The graphs have become too small again in small screens.
Should tinker around with the values.

### LINKED ISSUE #67: Unorganized match number
Matches can be submitted in the wrong order, the parser should organize the data according to match numbers.

### LINKED ISSUE #73: Add Option To Edit Submitted Matches
There should be a screen where it is possible to edit already submitted data.

### PR DESCRIPTION
**Pull request by ScarletMetal**
fixes #73
fixes #60 
fixes #67

closes #79

### CODE REVIEW

File: src/util/scouting-form-manager.js [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+      })
+  })
+}
+function loadFromMemory () {
+  return JSON.parse(localStorage.getItem('scouting-form'))
+}
+
+export default {
+  getFromServer,
+  loadFromStorage: loadFromMemory
```
Comment (YonatanNitzan) [inline src/util/scouting-form-manager.js]: Sure that's correct?
It seems conceptually wrong...

File: src/components/charts/bar.js [hunk 2]
```diff
@@ -17,8 +17,13 @@ export default (title, chartRecipe) => {
           }
         ]
       }}
-      height={'30vh'}
-      width={'100%'}
+      height={
+        (() => {
+          if (getScreenOrientation() === 'land') return '30vw'
+          else return ''
```
[the remark this answers is not in the document]
Comment (TheArchNemesis) [reply src/components/charts/bar.js]: Yes. it just works

File: src/util/scouting-form-manager.js (hunk 1 above)
Comment (TheArchNemesis) [reply src/util/scouting-form-manager.js]: it removes Network load, because it dosent request the form each time

File: src/components/charts/bar.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (YonatanNitzan) [reply src/components/charts/bar.js]: Lol ok

File: src/util/scouting-form-manager.js (hunk 1 above)
Comment (YonatanNitzan) [reply src/util/scouting-form-manager.js]: Oh okie

**Review by Antimality — APPROVED** [review]
